[package]
name = "respot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
librespot = { git = "https://github.com/librespot-org/librespot", features = ["pulseaudio-backend"] }
