#ifndef LIBRESPOT_OAUTH_SCOPES_H
#define LIBRESPOT_OAUTH_SCOPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum Scope {
    APP_REMOTE_CONTROL,
    PLAYLIST_MODIFY,
    PLAYLIST_MODIFY_PRIVATE,
    PLAYLIST_MODIFY_PUBLIC,
    PLAYLIST_READ,
    PLAYLIST_READ_COLLABORATIVE,
    PLAYLIST_READ_PRIVATE,
    STREAMING,
    UGC_IMAGE_UPLOAD,
    USER_FOLLOW_MODIFY,
    USER_FOLLOW_READ,
    USER_LIBRARY_MODIFY,
    USER_LIBRARY_READ,
    USER_MODIFY,
    USER_MODIFY_PLAYBACK_STATE,
    USER_MODIFY_PRIVATE,
    USER_PERSONALIZED,
    USER_READ_BIRTHDATE,
    USER_READ_CURRENTLY_PLAYING,
    USER_READ_EMAIL,
    USER_READ_PLAY_HISTORY,
    USER_READ_PLAYBACK_POSITION,
    USER_READ_PLAYBACK_STATE,
    USER_READ_PRIVATE,
    USER_READ_RECENTLY_PLAYED,
    USER_TOP_READ
} Scope;

#ifdef __cplusplus
}
#endif

#endif // LIBRESPOT_OAUTH_SCOPES_H
